#!/bin/bash
set -e
branch="$(git branch | grep '^\* .*' | tr -d '* ')"

echo -e "Your current branch is \033[1;35m$branch\033[0m"

echo -e "\033[1;32m gitstart; use in master branch; for starting work\033[0m"
echo -e "\033[1;32m gitprep; use in feature branch; will rebase and push to github fork \033[0m"
echo -e "\033[1;32m          also use this for amending to pull requests\033[0m"
echo -e "\033[1;32m gitpullreq; use in feature branch; will create a pull req\033[0m"
echo -e "\033[1;32m gitfinish; use in feature branch; will delete current feature branch\033[0m"
echo -e "\033[1;32m gitpo='git push origin <currentbranch>'  \033[0m"
