#!/bin/bash
set -e
branch="$(git branch | grep '^\* .*' | tr -d '* ')"

echo -e "Your current branch is \033[1;35m$branch\033[0m"

echo -e "\033[1;32m gits='git status ' \033[0m"
echo -e "\033[1;32m gita='git add '    \033[0m"
echo -e "\033[1;32m gitb='git branch ' \033[0m"
echo -e "\033[1;32m gitc='git commit'  \033[0m"
echo -e "\033[1;32m gitd='git diff'    \033[0m"
echo -e "\033[1;32m gith='git hist'    \033[0m"
echo -e "\033[1;32m gitco='git checkout'\033[0m"
echo -e "\033[1;32m gitk='gitk --all&' \033[0m"
echo -e "\033[1;32m gitx='gitx --all'  \033[0m"
echo -e "\033[1;32m gitpom='git push origin master'  \033[0m"
echo -e "\033[1;32m gitpo='git push origin <currentbranch>'  \033[0m"
echo -e "\033[1;32m gitpull='git pull --rebase upstream master\033[0m"
