#!/bin/bash
set -e

echo -e "\033[1;35m----CREATING PULL REQUEST----\033[0m"

echo -e "\033[32mCreating a new pull request template\033[0m"
repodir="$(git rev-parse --show-toplevel)"
touch ~/newreq.md
rm -f ~/newreq.md
echo "cp -n $repodir/.github/PULL_REQUEST_TEMPLATE.md ~/newreq.md"
cp -n $repodir/.github/PULL_REQUEST_TEMPLATE.md ~/newreq.md
vim ~/newreq.md
# Must cd back or hub will freakout below
`cd $repodir`

# Create proper string for pull request
upstream="$(git remote -v | grep '^upstream.*(push)' | sed -E -e 's/^upstream//' -e 's/^[^a-z]//' -e 's/^.*github.com:?\/?//' -e 's/\.git.+/:master/')"

echo -e "\033[32m####hub pull-request -F ~/newreq.md -b $upstream \033[0m"
hub pull-request -F ~/newreq.md -b $upstream

rm -f ~/newreq.md

echo -e "\033[1;35m####Final status: \033[0m"
git status

