#!/bin/bash
set -e
echo -e "\033[1;35m----PREPPING WORK----\033[0m"

echo -e "\033[32m####git pull --rebase upstream master\033[0m"
git pull --rebase upstream master

branch="$(git branch | grep '^\* .*' | tr -d '* ')"
echo -e "\033[1;32m####git push origin $branch\033[0m"
`git push origin $branch`

echo -e "\033[1;35m####Final status: \033[0m"
git status

