#!/bin/bash
set -e
echo -e "\033[1;35m----STARTING WORK----\033[0m"

echo -e "\033[32m####git pull --rebase upstream master\033[0m"
git pull --rebase upstream master

echo -e "\033[32m####git checkout -b $1\033[0m"
git checkout -b $1

echo -e "\033[32m####npm install\033[0m"
npm install

echo -e "\033[1;35m####Final status: \033[0m"
git status

