#!/bin/bash
set -e

IFS=':' read -ra vars <<< "$1"
user=${vars[0]}
branch=${vars[1]}
gitfile="$(git remote -v | grep '^origin.*(fetch)$' | sed -E -e 's/^.*\///' -e 's/ \(fetch\)//')"

echo -e "user: $user, branch: $branch, gitfile: $gitfile"

echo -e "\033[32mgit checkout -b mergeme-$user-$branch\033[0m"
git checkout -b merging-$user-$branch
echo -e "\033[32mgit pull https://github.com/$user/$gitfile $branch\033[0m"
git pull https://github.com/$user/$gitfile $branch
echo -e "\033[32mgit checkout master\033[0m"
git checkout master
echo -e "\033[32mgit pull --rebase upstream master\033[0m"
git pull --rebase upstream master
echo -e "\033[32mgit merge mergeme-$user-$branch\033[0m"
git merge merging-$user-$branch
echo -e "\033[32mgit push upstream master\033[0m"
git push upstream master
echo -e "\033[32mgit push origin master\033[0m"
git push origin master
echo -e "\033[32mgit branch -d mergeme-$user-$branch\033[0m"
git branch -d merging-$user-$branch

