#!/bin/bash
set -e

branch="$(git branch | grep '^\* .*' | tr -d '* ')"
if [ $branch = 'master' ];
then
  echo -e "\033[1;31mYou cannot run this script on branch master"
  exit 1
fi

echo -e "\033[1;35m----FINISHING MANUAL MERGE----\033[0m"

echo -e "\033[32mgit checkout master\033[0m"
git checkout master
echo -e "\033[32mgit pull --rebase upstream master\033[0m"
git pull --rebase upstream master
echo -e "\033[32mgit merge $branch\033[0m"
git merge $branch
echo -e "\033[32mgit push upstream master\033[0m"
git push upstream master
echo -e "\033[32mgit push origin master\033[0m"
git push origin master
echo -e "\033[32mgit branch -d $branch\033[0m"
git branch -d $branch

cd $(git rev-parse --show-toplevel)
npm run docs
cd docs/esdoc
git add .
git commit -m "Auto-update docs"
git push origin master
cd ../../

